jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install LLVM 21
        run: |
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)" 21
          sudo apt-get install -y clang-21 lld-21 llvm-21 llvm-21-dev

          # symlink to make clang 21 the default
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-21 200
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-21 200
          sudo update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/ld.lld-21 200
          sudo update-alternatives --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-21 200
          sudo update-alternatives --install /usr/bin/llvm-nm llvm-nm /usr/bin/llvm-nm-21 200
          sudo update-alternatives --install /usr/bin/llvm-objcopy llvm-objcopy /usr/bin/llvm-objcopy-21 200
          sudo update-alternatives --install /usr/bin/llvm-objdump llvm-objdump /usr/bin/llvm-objdump-21 200
          sudo update-alternatives --install /usr/bin/llvm-strip llvm-strip /usr/bin/llvm-strip-21 200

      - name: Build kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export LLVM=1
          export CC=clang
          export LD=ld.lld
          export AR=llvm-ar
          export NM=llvm-nm
          export OBJCOPY=llvm-objcopy
          export OBJDUMP=llvm-objdump
          export STRIP=llvm-strip
          export LLVM_IAS=1

          make O=out vendor/veux-qgki_defconfig
          make -j$(nproc) O=out
